stages:
  prepare:
    cmd: python src/preprocessing.py
    deps:
      - data/boston.csv
      - src/preprocessing.py
    outs:
      - data/X_train.parquet
      - data/X_val.parquet
      - data/X_test.parquet
      - data/y_train.parquet
      - data/y_val.parquet
      - data/y_test.parquet
      - data/X_train_pca.parquet
      - data/X_val_pca.parquet
      - data/X_test_pca.parquet
