apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-ui
  template:
    metadata:
      labels:
        app: mlflow-ui
    spec:
      containers:
      - name: mlflow-ui
        image: mlflow-ui
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5001"]
