# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: app-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: app
#   template:
#     metadata:
#       labels:
#         app: app
#     spec:
#       containers:
#       - name: app
#         image: app:app
#         imagePullPolicy: Never
#         ports:
#         - containerPort: 8000

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment-fixed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: us-west1-docker.pkg.dev/lab9-458605/lab9/app:app2
        ports:
        - containerPort: 8000